'use strict';
const $=id=>document.getElementById(id);
const labels={heat_c:'Temperature (°C)',rate_per_1000:'Events / 1,000 synthetic people',rain_mm:'Rainfall (mm/month)'};
let dataset,selected=0,timer=null,plotlyPromise;
const stops=[[27,44,99],[36,108,142],[37,173,154],[185,223,90],[250,230,141]];
function color(v,min,max){const f=Math.max(0,Math.min(.99999,(v-min)/(max-min)))*4,i=Math.floor(f),t=f-i;return `rgb(${stops[i].map((n,j)=>Math.round(n*(1-t)+stops[i+1][j]*t)).join(',')})`;}
function scale(metric){const a=dataset.values[metric].flat();return [Math.min(...a),Math.max(...a)];}
function mapSVG(t,x=0,y=0,size=400,metric=$('metric').value){const [min,max]=scale(metric),d=size/8;let s=`<g transform="translate(${x},${y})">`;
dataset.cells.forEach(c=>{const v=dataset.values[metric][t][c.cell_id];s+=`<rect class="grid-cell ${selected===c.cell_id?'selected':''}" data-cell="${c.cell_id}" x="${c.col*d}" y="${(7-c.row)*d}" width="${d}" height="${d}" fill="${color(v,min,max)}" role="button" tabindex="0" aria-label="Select cell ${c.cell_id}, ${labels[metric]} ${v.toFixed(1)}"><title>Cell ${c.cell_id}: ${v.toFixed(1)}</title></rect>`;});return s+'</g>';}
function series(metric,t){const v=dataset.values[metric].map(a=>a[selected]),[min,max]=scale(metric),x=i=>45+i*300/23,y=n=>155-(n-min)/(max-min)*125;
return `<svg viewBox="0 0 370 205" role="img" aria-label="Time series for cell ${selected}, all 24 months"><line x1="45" y1="155" x2="345" y2="155" stroke="#819da9"/><line x1="45" y1="30" x2="45" y2="155" stroke="#819da9"/><text x="40" y="30" fill="#abc3d0" font-size="11" text-anchor="end">${max.toFixed(1)}</text><text x="40" y="158" fill="#abc3d0" font-size="11" text-anchor="end">${min.toFixed(1)}</text><polyline points="${v.map((n,i)=>`${x(i)},${y(n)}`).join(' ')}" fill="none" stroke="#69e3e7" stroke-width="2.5"/><line x1="${x(t)}" x2="${x(t)}" y1="25" y2="155" stroke="#f4cc7a" stroke-dasharray="4 4"/><circle cx="${x(t)}" cy="${y(v[t])}" r="5" fill="#f4cc7a"/><text x="45" y="180" fill="#abc3d0" font-size="12">Month 1</text><text x="285" y="180" fill="#abc3d0" font-size="12">Month 24</text><text x="190" y="200" fill="#abc3d0" font-size="12" text-anchor="middle">${labels[metric]}</text></svg>`;}
async function loadPlotly(){if(window.Plotly)return;if(!plotlyPromise)plotlyPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.plot.ly/plotly-3.1.0.min.js';s.onload=resolve;s.onerror=()=>reject(Error('Plotly CDN unavailable'));document.head.appendChild(s);});return plotlyPromise;}
async function cube(metric,t){try{await loadPlotly();if($('view').value!=='cube')return;const x=[],y=[],z=[],c=[];for(let time=0;time<24;time+=2)dataset.cells.forEach(cell=>{x.push(cell.lon);y.push(cell.lat);z.push(time+1);c.push(dataset.values[metric][time][cell.cell_id]);});const [min,max]=scale(metric);await Plotly.react('cube',[{type:'scatter3d',mode:'markers',x,y,z,marker:{size:3,color:c,cmin:min,cmax:max,colorscale:stops.map((v,i)=>[i/4,`rgb(${v})`]),colorbar:{title:{text:labels[metric]},thickness:12}},hovertemplate:'lon %{x:.3f}<br>lat %{y:.3f}<br>Month %{z}<br>Value %{marker.color:.1f}<extra>Synthetic</extra>'}],{margin:{l:0,r:20,t:10,b:0},paper_bgcolor:'#102332',font:{color:'#eaf4f7'},scene:{xaxis:{title:{text:'Longitude'}},yaxis:{title:{text:'Latitude'}},zaxis:{title:{text:'Month'}}}},{responsive:true,displaylogo:false});}catch(e){$('cube').textContent='The interactive cube needs WebGL and the Plotly CDN. Use the 2D map, map matrix, or data table instead.';}}
function render(){if(!dataset)return;const metric=$('metric').value,t=Number($('month').value),view=$('view').value,[min,max]=scale(metric);$('month-label').value=t+1;$('scale-label').textContent=`${min.toFixed(1)} – ${max.toFixed(1)} · fixed scale`;$('spatial').hidden=view==='cube';$('cube').hidden=view!=='cube';
if(view==='map'){$('spatial').innerHTML=`<svg viewBox="0 0 510 480" aria-label="Synthetic geographic grid, north at top"><text x="250" y="22" fill="#abc3d0" text-anchor="middle">North ↑ · Month ${t+1}</text>${mapSVG(t,65,35,400)}<text x="65" y="456" fill="#abc3d0" font-size="13">25.85° E</text><text x="400" y="456" fill="#abc3d0" font-size="13">26.05° E</text><text x="5" y="50" fill="#abc3d0" font-size="11">24.55° S</text><text x="5" y="430" fill="#abc3d0" font-size="11">24.75° S</text></svg>`;$('view-note').textContent='North is up. Coordinates locate a fictional grid; no basemap or observed health layer is used.';}
else if(view==='matrix'){let s='<svg viewBox="0 0 660 480" aria-label="Six monthly maps on a common scale">';[0,4,8,12,16,20].forEach((m,i)=>{const x=10+(i%3)*220,y=25+Math.floor(i/3)*240;s+=`<text x="${x}" y="${y-8}" fill="#abc3d0" font-size="13">Month ${m+1}</text>${mapSVG(m,x,y,200)}`;});$('spatial').innerHTML=s+'</svg>';$('view-note').textContent='Months 1, 5, 9, 13, 17, and 21 share one scale. Compare patterns without relying on memory. The slider updates the linked series and table.';}
else{cube(metric,t);$('view-note').textContent='The vertical axis is time, not height. Every other month is shown to reduce occlusion. Drag to orbit; use the table for exact values.';}
$('view-title').textContent=labels[metric];const cell=dataset.cells[selected];$('cell-title').textContent=`Cell ${selected}`;$('cell-select').value=selected;$('cell-summary').textContent=`Month ${t+1}: ${dataset.values[metric][t][selected].toFixed(2)}. Invented population: ${cell.population.toLocaleString()}.`;$('series').innerHTML=series(metric,t);$('metric-heading').textContent=labels[metric];$('table-caption').textContent=`Month ${t+1} · synthetic data · ${labels[metric]}`;$('table-body').innerHTML=dataset.cells.map(c=>`<tr><td>${c.cell_id}</td><td>${c.lon.toFixed(4)}</td><td>${c.lat.toFixed(4)}</td><td>${c.population}</td><td>${dataset.values[metric][t][c.cell_id].toFixed(2)}</td></tr>`).join('');$('status').textContent='64 cells × 24 months · seed 2026 · units and methods in notebooks/rewiring.py';}
function select(target){if(target.dataset.cell!==undefined){selected=Number(target.dataset.cell);render();}}
$('spatial').addEventListener('click',e=>select(e.target));$('spatial').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(e.target);}});
['month','metric','view'].forEach(id=>$(id).addEventListener('input',render));$('cell-select').addEventListener('change',e=>{selected=Number(e.target.value);render();});
function stop(){clearInterval(timer);timer=null;$('play').textContent='Play months';$('play').setAttribute('aria-pressed','false');}
$('play').onclick=()=>{if(timer){stop();return;}timer=setInterval(()=>{$('month').value=(Number($('month').value)+1)%24;render();},750);$('play').textContent='Pause';$('play').setAttribute('aria-pressed','true');};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
$('download').onclick=()=>{if(!dataset)return;const t=Number($('month').value),metric=$('metric').value;const features=dataset.cells.map(c=>{const x=c.lon,y=c.lat,d=.0125;return {type:'Feature',geometry:{type:'Polygon',coordinates:[[[x-d,y-d],[x+d,y-d],[x+d,y+d],[x-d,y+d],[x-d,y-d]]]},properties:{cell_id:c.cell_id,population:c.population,month:t+1,[metric]:dataset.values[metric][t][c.cell_id],data_status:'synthetic',license:'CC-BY-4.0',source:'rewiring.py; seed=2026'}};});const url=URL.createObjectURL(new Blob([JSON.stringify({type:'FeatureCollection',features},null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download=`synthetic-${metric}-month-${t+1}.geojson`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
fetch('data/cube.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json();}).then(d=>{dataset=d;$('cell-select').innerHTML=d.cells.map(c=>`<option value="${c.cell_id}">Cell ${c.cell_id}</option>`).join('');render();}).catch(()=>{$('status').textContent='Could not load the bundled data. Serve this folder over HTTP or use the notebook examples.';});
